name: ci
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy-image:
    runs-on: ubuntu-latest
    steps:
      # 拉取master分支
      - name: Checkout
        uses: actions/checkout@master
      # 设置qemu来编译多个平台的镜像
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # 设置buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # 编译并且推送到dockerhub
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          tags: |
            bboysoul/miwifi-exporter:latest
            bboysoul/miwifi-exporter:v1.0.0
